name: linting
inputs:
  cwd:
    required: false
    default: ${{ github.workspace }}
runs:
  using: composite
  steps:
  - name: Linting
    run: |-
      cd ${{ inputs.cwd }}
      npm run lint
    shell: bash
