name: setup_windows
inputs:
  cwd:
    required: false
    default: ${{ github.workspace }}
description: "Setup Windows Machine"
runs:
  using: composite
  steps:
    - name: Install Dependencies
      run: |-
        # Install node dependencies
        npm ci
      shell: bash
